DEFAULT:
        calibration: calibrations/HWLICENCE.npz
        neuron_params:
                leak: 0.70
                threshold: 1.08
                g_leak: 4.
                tau_syn: 1.
        scale_weights: 30
        synapse_bias: 1000
        taum : 6.
